version: 2

sources:
  - name: silver
    # in GCP it's project id
    database: just-camera-454714-e8
    # dataset
    schema: dev_project_dataset_pebbles

    tables:
      - name: fct_silver_table