version: 2

sources:
  - name: staging
    # in GCP it's project id
    database: just-camera-454714-e8
    # dataset
    schema: dev_project_dataset_pebbles

    tables:
      - name: bronze_table

models:
  - name: stg_bronze_table
    description: ""
    columns:
      - name: observation_id
        data_type: string
        description: ""
        tests:
          - unique:
            severity: warn
          - not_null:
            severity: warn

      - name: station
        data_type: string
        description: ""

      - name: observation_time
        data_type: timestamp
        description: ""

      - name: lon
        data_type: float64
        description: ""

      - name: lat
        data_type: float64
        description: ""

      - name: air_temperature
        data_type: float64
        description: ""

      - name: dew_point_temperature
        data_type: float64
        description: ""

      - name: relative_humidity
        data_type: float64
        description: ""

      - name: wind_direction
        data_type: float64
        description: ""

      - name: wind_speed
        data_type: float64
        description: ""

      - name: precipitation
        data_type: float64
        description: ""

      - name: pressure_altimeter
        data_type: float64
        description: ""

      - name: sea_level_pressure
        data_type: float64
        description: ""

      - name: visibility
        data_type: float64
        description: ""

      - name: wind_gust
        data_type: float64
        description: ""

      - name: sky_level_1_coverage
        data_type: string
        description: ""

      - name: sky_level_2_coverage
        data_type: string
        description: ""

      - name: sky_level_3_coverage
        data_type: string
        description: ""

      - name: sky_level_4_coverage
        data_type: string
        description: ""

      - name: sky_level_1_altitude
        data_type: float64
        description: ""

      - name: sky_level_2_altitude
        data_type: float64
        description: ""

      - name: sky_level_3_altitude
        data_type: float64
        description: ""

      - name: sky_level_4_altitude
        data_type: float64
        description: ""

      - name: present_weather_code
        data_type: string
        description: ""

      - name: ice_accretion_1hr
        data_type: float64
        description: ""

      - name: ice_accretion_3hr
        data_type: float64
        description: ""

      - name: ice_accretion_6hr
        data_type: float64
        description: ""

      - name: peak_wind_gust
        data_type: float64
        description: ""

      - name: peak_wind_drct
        data_type: float64
        description: ""

      - name: peak_wind_time
        data_type: float64
        description: ""

      - name: apparent_temperature
        data_type: float64
        description: ""

      - name: snow_depth
        data_type: float64
        description: ""