version: 2

sources:
  - name: staging
    # in GCP it's project id
    database: just-camera-454714-e8
    # dataset
    schema: dev_project_dataset_pebbles

    tables:
      - name: bronze_table

models:
  - name: stg_bronze_table
    description: "loaded bronze layer data with limited transformation, including adding primary key and renaming columns"
    columns:
      - name: observation_id
        data_type: string
        description: "created by hashing observation_time and station"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: station
        data_type: string
        description: "three or four character site identifier"
        tests:
          - not_null:
              severity: warn

      - name: observation_time
        data_type: timestamp
        description: "timestamp of the observation"
        tests:
          - not_null:
              severity: warn

      - name: lon
        data_type: float64
        description: ""

      - name: lat
        data_type: float64
        description: ""

      - name: air_temperature
        data_type: float64
        description: "Air Temperature in Fahrenheit, typically @ 2 meters"

      - name: dew_point_temperature
        data_type: float64
        description: "Dew Point Temperature in Fahrenheit, typically @ 2 meters"

      - name: relative_humidity
        data_type: float64
        description: "Relative Humidity in %"

      - name: wind_direction
        data_type: float64
        description: "Wind Direction in degrees from *true* north"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              severity: warn
          - dbt_utils.expression_is_true:
              expression: "<= 360"
              severity: warn

      - name: wind_speed
        data_type: float64
        description: "Wind Speed in knots"

      - name: precipitation
        data_type: float64
        description: "One hour precipitation for the period from the observation time to the time of the previous hourly precipitation reset. This varies slightly by site. Values are in inches. This value may or may not contain frozen precipitation melted by some device on the sensor or estimated by some other means. Unfortunately, we do not know of an authoritative database denoting which station has which sensor."

      - name: pressure_altimeter
        data_type: float64
        description: "Pressure altimeter in inches"

      - name: sea_level_pressure
        data_type: float64
        description: "Sea Level Pressure in millibar"

      - name: visibility
        data_type: float64
        description: "Visibility in miles"

      - name: wind_gust
        data_type: float64
        description: "Wind Gust in knots"

      - name: sky_level_1_coverage
        data_type: string
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('valid_sky_level_coverage') }}"
              severity: warn

      - name: sky_level_2_coverage
        data_type: string
        description: ""

      - name: sky_level_3_coverage
        data_type: string
        description: ""

      - name: sky_level_4_coverage
        data_type: string
        description: ""

      - name: sky_level_1_altitude
        data_type: float64
        description: ""

      - name: sky_level_2_altitude
        data_type: float64
        description: ""

      - name: sky_level_3_altitude
        data_type: float64
        description: ""

      - name: sky_level_4_altitude
        data_type: float64
        description: ""

      - name: present_weather_code
        data_type: string
        description: "Present Weather Codes (space seperated)"

      - name: ice_accretion_1hr
        data_type: float64
        description: ""

      - name: ice_accretion_3hr
        data_type: float64
        description: ""

      - name: ice_accretion_6hr
        data_type: float64
        description: ""

      - name: peak_wind_gust
        data_type: float64
        description: "Peak Wind Gust (from PK WND METAR remark) (knots)"

      - name: peak_wind_drct
        data_type: float64
        description: "Peak Wind Gust Direction (from PK WND METAR remark) (deg)"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              severity: warn
          - dbt_utils.expression_is_true:
              expression: "<= 360"
              severity: warn

      - name: peak_wind_time
        data_type: float64
        description: "Peak Wind Gust Time (from PK WND METAR remark)"

      - name: apparent_temperature
        data_type: float64
        description: "Apparent Temperature (Wind Chill or Heat Index) in Fahrenheit"

      - name: snow_depth
        data_type: float64
        description: ""
