name: CI for dbt

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dbt/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/.google/credentials/stg-sa-key.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Write GCP service account key
        run: |
          mkdir -p dbt/.google/credentials
          echo "${{ secrets.GCP_CREDENTIALS_STAGING }}" > dbt/.google/credentials/stg-sa-key.json

      - name: Install dbt with sudo
        run: |
          sudo pip install dbt
          dbt --version
      
      - name: Install dbt BigQuery support
        run: |
          pip install --user dbt-bigquery
          dbt --version

      - name: Generate profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          default:
            target: staging
            outputs:
              staging:
                type: bigquery
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: ${{ secrets.GCP_BIGQUERY_DATASET }}
                threads: 1
                keyfile: dbt/.google/credentials/stg-sa-key.json
                location: US
                timeout_seconds: 300
          " > ~/.dbt/profiles.yml
      
      - name: Install Dbt dependencies
        run: |
          export DBT_PROJECT_DIR=/home/runner/work/DE-Project/DE-Project/dbt
          dbt deps --profiles-dir ~/.dbt/profiles.yml --project-dir $DBT_PROJECT_DIR


      # - name: Install Dbt dependencies
      #   run: |
      #     dbt deps
      
      # - name: Generate profiles.yml
