name: CI for load raw data dag

on:
  pull_request:
    branches:
      - main
    paths:
      - 'airflow/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation
      
      - name: Build Docker image
        run: |
          docker build --cache-from=ci-test-for-load-image -t ci-test-for-load-image -f docker/Dockerfile .
      
      - name: Run Docker compose
        run: |
          docker-compose -f docker/docker-compose.yml up -d
      
      - name: Run unit tests
        run: |
          docker-compose run --rm test-container pytest tests/unit/test_load_to_bucket.py


      # - name: Run integration tests

      # - name: Stop Docker containers
      #   run: |
      #    docker-compose -f docker/docker-compose.yml down

