name: CI for dbt

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dbt/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Write GCP service account key
        run: |
          mkdir -p dbt/.google/credentials
          echo "${{ secrets.GCP_CREDENTIALS_STAGING }}" > dbt/.google/credentials/stg-sa-key.json

      - name: Install dbt with sudo
        run: |
          sudo pip install dbt
          dbt --version
      
      - name: Install dbt BigQuery support
        run: |
          pip install --user dbt-bigquery
          dbt --version

      - name: Generate profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          default:
            target: staging
            outputs:
              staging:
                type: bigquery
                method: service-account-json
                project: ${{ secrets.GCP_PROJECT_ID }}
                dataset: ${{ secrets.GCP_BIGQUERY_DATASET }}
                threads: 1
                keyfile_json:
                  type: service_account
                  project_id: just-camera-454714-e8
                  private_key_id: be9b518aba181b80b8416b814c3045c7584347af
                  private_key: ${{ secrets.GCP_PRIVATE_KEY }}
                  client_email: staging-terraform-sa@***.iam.gserviceaccount.com
                  client_id: 110582212550182543890
                  auth_uri: https://accounts.google.com/o/oauth2/auth
                  token_uri: https://oauth2.googleapis.com/token
                  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
                  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/staging-terraform-sa%40***.iam.gserviceaccount.com
                location: US
                timeout_seconds: 300
          " > ~/.dbt/profiles.yml
      
      - name: Install Dbt dependencies
        run: |
          export DBT_PROJECT_DIR=/home/runner/work/DE-Project/DE-Project/dbt
          dbt deps --profiles-dir ~/.dbt/profiles.yml --project-dir $DBT_PROJECT_DIR
      
      - name: Dbt build
        run: |
          export DBT_PROJECT_DIR=/home/runner/work/DE-Project/DE-Project/dbt
          export DBT_PROFILES_DIR=/home/runner/.dbt  # 使用绝对路径指定 profiles.yml
          echo "Profiles path: $DBT_PROFILES_DIR/profiles.yml"
          cat $DBT_PROFILES_DIR/profiles.yml  # 打印文件内容，确保文件生成成功
          
          # 确保 dbt 读取到正确的环境变量
          echo "DBT_PROFILES_DIR is set to: $DBT_PROFILES_DIR"
          
          export DBT_GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          echo "DBT_GCP_PROJECT_ID is set to $DBT_GCP_PROJECT_ID"

          export DBT_GCP_BIGQUERY_DATASET="${{ secrets.GCP_BIGQUERY_DATASET }}"
          echo "DBT_GCP_BIGQUERY_DATASET is set to $DBT_GCP_BIGQUERY_DATASET"
          
          dbt debug --profiles-dir $DBT_PROFILES_DIR --project-dir $DBT_PROJECT_DIR
          dbt build --profiles-dir $DBT_PROFILES_DIR --project-dir $DBT_PROJECT_DIR

     